### ISSUE TITLE
The month of the "Last update" date in the Preferences panel shows up as "undefined"

### ISSUE THREAD

**Issue by AlessandroMenti** [Noitidart/Smart-Zoom#11]
If you open the Preferences panel, the month of the "Last update" date shows up as "undefined".

**Steps to reproduce:**
1. Start Firefox Developer Edition (I tested it on today's build, the Italian "FF Dev 50.0a2 (2016-09-02)" for Linux x64, prebuilt by Mozilla, with a fresh profile).
2. Open the hamburger menu, choose *Addons*, search for *smart zoom*, click on *Install* next to the *Smart Zoom* addon to install the addon.
3. When the addon is installed, click on *Preferences* next to the addon name to open the Preferences panel.

**Expected results:**
The *Last update* date shows up as *September 2, 2016* (in your language).

**Actual results:**
The *Last update* date shows up as *undefined 2, 2016*.

**Comment by Noitidart** [comment]
Found it and fixed. Thanks for your super detailed test results! The issues was a whitespace before the `=` in some locales in the `chrome://global/locale/dateFormat.properties` file.
