### ISSUE TITLE
Options to choose the zoom ratio (1/2 screen or 3/4 screen)

### ISSUE THREAD

**Issue by Eremos** [Noitidart/Smart-Zoom#6]
I have a screen who is 19" wide. I have difficulties to read small characters, but when zoomr enlarge the text, it is far too big. I would appreciate if it is possible to set the zoom ratio, ie 3/4 or 1/2 of the screen, or enlarge the text from 100% to 150%.
Thank you

**Comment by Noitidart** [comment]
This feature has landed in the update, if you go to options you can set a "Margin" around the zoom element. Please try it out.
