### ISSUE TITLE
please add some margin or the option for some margin

### ISSUE THREAD

**Issue by nadler** [Noitidart/Smart-Zoom#7]
I really like using this add-on, since switching from Safari to Firefox had caused me to lose the Smart Zoom functionality.  

However, this add-on results in much lower readability than the Apple Safari Smart Zoom.  The zoom goes all the way edge to edge, removing the margin entirely.  This makes it hard to read the start of lines.  It would be great to add some margin or at least allow an option to add some.

Please see the attached images.  One is Zoomr in Firefox and the other is Safari Smart Zoom.  In both I had the browser up against another application on the left side of the browser window.
![zoomr](https://cloud.githubusercontent.com/assets/5439597/8940816/8b363598-3531-11e5-8e66-c75a57b42b50.png)
![safari](https://cloud.githubusercontent.com/assets/5439597/8940823/8fc693aa-3531-11e5-83e8-e51b3fb63877.png)

**Comment by Noitidart** [comment]
Thank you so much for this feedback this is a good idea. I also want to impelment the preference to control the mouse down timing.

**Comment by Noitidart** [comment]
This has landed in the "Smart Zoom" which is the next version of Zoomr. You can do this from the preferences page. Please try it out.
