### ISSUE TITLE
Allow notifications to be disabled

### ISSUE THREAD

**Issue by nadler** [Noitidart/Smart-Zoom#8]
Another enhancement request I have is to allow notifications to be suppressed.  I don't really need banners flashing into my Mac's OS notification area when I zoom a web page and when I zoom back.  The notifications pull my attention away from the web page I want to zoom in to read.

I love this add-on, please keep up the good work!

I have added an image showing what the notification does on a Mac in case you don't have one:

![screen shot 2015-07-31 at 8 35 22 am](https://cloud.githubusercontent.com/assets/5439597/9008623/26d17e32-3761-11e5-98af-147f94d0e529.png)

**Comment by Noitidart** [comment]
Thanks these are simple things I'll try to implement this weekend :)

**Comment by sergeevabc** [comment]
@Noitidart, any progress? Please, give us an option to turn these notifications off.

**Comment by Noitidart** [comment]
Hey there @sergeevabc  thanks so much for your patience. In the last 6 months I was learning the new e10s system and finding ways to keep my addons alive in the future. I'm going to revisit this very soon. Just putting the finishing touches on MouseControl. Thanks so much for your patience! :)

**Comment by sergeevabc** [comment]
Patience is over: removed Zoomr.

**Comment by nadler** [comment]
I'm not sure if this works for anyone else, but Google Chrome has now added native smart zoom support.  So, I have switched to Google Chrome since it has better smart zoom support than any Firefox option at the current time.  I'll re-evaluate in the future if Zoomr improves, thanks for your work Noitidart.

**Comment by Noitidart** [comment]
Hi @nadler can you please show me how that Google Chrome smart zoom is working. Do you double click and it zooms?

**Comment by Noitidart** [comment]
Finally updated. Joined effort with Francesco, no more notifications.
